/** Display labels for staff fields (UI). CSV import matches Google Form headers. */
export const STAFF_FIELD_LABELS = {
  formSubmittedAt: 'Form submitted',
  profileImageUrl: 'Profile photo',
  nameWithInitials: 'Name with initials',
  name: 'Full name',
  nic: 'National Identity Card number',
  registrationNumber: 'Registration number',
  classAndGrade: 'Class and grade',
  dateOfBirth: 'Date of birth',
  gender: 'Gender',
  maritalStatus: 'Marital status',
  spouseName: 'Spouse name',
  spouseAddress: 'Spouse address',
  spousePhone: 'Spouse telephone',
  firstAppointmentDate: 'Date of first appointment',
  joinedDate: 'Date of appointment to this school',
  previousSchools: 'Previously served schools',
  educationalQualifications: 'Educational qualifications',
  professionalQualifications: 'Professional qualifications',
  appointedSubject: 'Appointed subject',
  subjectsTaught: 'Subjects taught',
  gradesTaught: 'Grades taught',
  teacherNumber: "This school's teacher number",
  phone: 'Telephone number',
  whatsapp: 'WhatsApp number',
  email: 'Email address',
  staffClassification: 'Staff classification',
  address: 'Personal address',
  emergencyContactName: 'Emergency contact name',
  emergencyContactPhone: 'Emergency contact telephone',
  staffId: 'Staff ID',
  staffType: 'Staff type',
  designation: 'Designation',
  department: 'Department',
  status: 'Status',
  notes: 'Notes',
} as const;
