/** Display labels for student fields (UI). CSV import still matches numbered Google Form headers. */
export const STUDENT_FIELD_LABELS = {
  formSubmittedAt: 'Form submitted',
  nameWithInitials: 'Name with initials',
  name: 'Full name',
  profileImageUrl: 'Profile image',
  admissionNumber: 'Index number',
  nic: 'National Identity Card number',
  dateOfBirth: 'Date of birth',
  gender: 'Gender',
  religion: 'Religion',
  address: 'Address',
  phone: 'Telephone number',
  whatsapp: 'WhatsApp number',
  email: 'Email address',
  grade: 'Grade',
  section: 'Class',
  admissionDate: 'Date of admission to school',
  previousSchools: 'Schools previously attended',
  mediumOfStudy: 'Medium of study',
  aestheticsSubject: 'Aesthetic Studies',
  alSubjects: 'A/L subjects',
  parentName: 'Name of parent / guardian',
  parentPhone: 'Contact number of parent / guardian',
  parentNic: 'NIC number of parent / guardian',
  parentOccupation: 'Occupation of parent / guardian',
  siblings: 'Names of siblings',
  siblingGrades: 'Grades in which siblings study',
  specialDisabilities: 'Special disabilities',
} as const;
